"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓█](gray4)\
$os\
$username\
[](bg:orange fg:gray4)\
$directory\
[](fg:orange bg:purple)\
$git_branch\
$git_status\
[](fg:purple bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:yellow)\
$docker_context\
[](fg:yellow bg:magenta)\
$time\
[](fg:magenta)\
$line_break$character"""

palette = 'oldworld'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.oldworld]
bg = "#161617"
fg = "#c9c7cd"
subtext1 = "#b4b1ba"
subtext2 = "#9f9ca6"
subtext3 = "#8b8693"
subtext4 = "#6c6874"
bg_dark = "#131314"
black = "#27272a"
red = "#ea83a5"
green = "#90b99f"
yellow = "#e6b99d"
purple = "#aca1cf"
magenta = "#e29eca"
orange = "#f5a191"
blue = "#92a2d5"
cyan = "#85b5ba"
bright_black = "#353539"
bright_red = "#ed96b3"
bright_green = "#a7c8b3"
bright_yellow = "#eac5ae"
bright_purple = "#b7aed5"
bright_magenta = "#e8b0d4"
bright_orange = "#f6b0a2"
bright_blue = "#a7b3dd"
bright_cyan = "#97c0c4"
gray0 = "#18181a"
gray1 = "#1b1b1c"
gray2 = "#2a2a2c"
gray3 = "#313134"
gray4 = "#3b3b3e"

[os]
disabled = false
style = "bg:gray4 fg:fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:gray4 fg:fg"
style_root = "bg:gray4 fg:fg"
format = '[ $user ]($style)'

[directory]
style = "fg:bg_dark bg:orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"~" = ""
"SUNY OCC" = ""

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:bg bg:purple)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:bg bg:purple)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bg bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:bg_dark"
format = '[[ $symbol( $context) ](fg:bg_dark bg:yellow)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:orange"
format = '[[  $time ](fg:bg_dark bg:magenta)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:magenta)'
