wallpaper {
  monitor =
  path = ~/Pictures/Wallpapers/oldworld_4k.png
  fit_mode = cover
}

wallpaper {
  monitor = eDP-1
  path = ~/Pictures/Wallpapers/oldworld_mbp.png
  fit_mode = cover
}

#wallpaper {
#  monitor = desc:Technical Concepts Ltd 43S525
#  path = ~/Pictures/Wallpapers/oldworld_4k.png
#}

wallpaper {
  monitor = desc:Acer Technologies KGB271U X1 45280269A4204
  path = ~/Pictures/Wallpapers/oldworld_1440.png
  fit_mode = cover
}

splash = true
splash_opacity = 0.9
ipc = off
