# Fallback (default) wallpaper
wallpaper {
  monitor = 
  path = ~/Pictures/Wallpapers/oldworld_1440.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-2
  path = ~/Pictures/Wallpapers/oldworld_1440.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/Wallpapers/oldworld_1080.png
  fit_mode = cover
}

#wallpaper {
#  monitor = desc:Technical Concepts Ltd 43S525
#  path = ~/Pictures/Wallpapers/oldworld_4k.png
#}

splash = true
splash_opacity = 0.9
ipc = off
