# Set programs that you use
$terminal = ghostty # Be sure to set DEFAULT_TERM in your .zshrc
$fileManager = $terminal -e yazi
$menu = wofi --term=$terminal -i -S drun
$browser = firefox
$lock = hyprlock
$text = subl
$panel = ~/.config/nwg-panel/nwg_menu_launcher.sh
$logout_menu = wlogout --protocol layer-shell

