# Execute your favorite apps at launch
exec-once = xrandr --output HDMI-A-2 --primary  # Set HDMI-A-2 as Primary for games
exec-once = mako & hyprpaper & waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = systemctl --user start waybar-updates.service
exec-once = sleep 1; hyprlock
