windowrule = opacity 1.0 override 1.0 override, match:class ^(kitty)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(org.kde.dolphin)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(com.mitchellh.ghostty)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(mpv)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(discord)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(virt-manager)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(com.hypixel.HytaleLauncher)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(HytaleClient)$
windowrule = float on, size 400 600, match:class ^(galculator)$
windowrule = float on, border_size 0, match:class ^(zenity)$
windowrule = float on, size 600 300, match:title ^(iheartcams)$
windowrule = opacity 1.0 override 1.0 override, focus_on_activate 0, match:class ^(zen)$
windowrule = float on, match:title ^(.*Network Manager.*)$
layerrule = blur on, ignore_alpha 0, blur_popups on, match:namespace waybar
layerrule = blur on, ignore_alpha 0.1, match:namespace rofi
layerrule = blur on, ignore_alpha 0, match:namespace notifications
layerrule = blur_popups on, match:namespace zen

# Smart Gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace f[1]
