require("core.plugin_config.catppuccin")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.hyprlang")
require("ibl").setup({})

